import path from "node:path";
import { readFile } from "node:fs/promises";

import {
  copyDirectory,
  copyFileOrDirectory,
  countDirectoryFiles,
  directorySize,
  ensureDir,
  pathExists,
  readJson,
  writeJson,
  writeText
} from "./fs-utils.mjs";

const SUPPORTED_TARGETS = new Set(["claude-code", "codex"]);

function assertString(value, label) {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new Error(`${label} must be a non-empty string.`);
  }
}

function assertArray(value, label) {
  if (!Array.isArray(value) || value.length === 0) {
    throw new Error(`${label} must be a non-empty array.`);
  }
}

function ensureUniqueIds(items, label) {
  const seen = new Set();

  for (const item of items) {
    assertString(item.id, `${label}.id`);

    if (seen.has(item.id)) {
      throw new Error(`Duplicate ${label} id "${item.id}".`);
    }

    seen.add(item.id);
  }
}

async function loadManifest(packDir) {
  const manifestPath = path.join(packDir, "packsmith.json");

  if (!(await pathExists(manifestPath))) {
    throw new Error(`Missing manifest: ${manifestPath}`);
  }

  const manifest = await readJson(manifestPath);
  assertString(manifest.name, "manifest.name");
  assertString(manifest.description, "manifest.description");
  assertString(manifest.version, "manifest.version");
  assertArray(manifest.targets, "manifest.targets");
  assertArray(manifest.skills, "manifest.skills");

  for (const target of manifest.targets) {
    if (!SUPPORTED_TARGETS.has(target)) {
      throw new Error(`Unsupported target "${target}". Supported targets: ${Array.from(SUPPORTED_TARGETS).join(", ")}.`);
    }
  }

  manifest.prompts ??= [];

  if (!Array.isArray(manifest.prompts)) {
    throw new Error("manifest.prompts must be an array when present.");
  }

  ensureUniqueIds(manifest.skills, "skill");
  ensureUniqueIds(manifest.prompts, "prompt");

  for (const skill of manifest.skills) {
    assertString(skill.path, `skill "${skill.id}" path`);
    assertString(skill.description, `skill "${skill.id}" description`);
  }

  for (const prompt of manifest.prompts) {
    assertString(prompt.path, `prompt "${prompt.id}" path`);
    assertString(prompt.description, `prompt "${prompt.id}" description`);
  }

  return { manifestPath, manifest };
}

async function validateAssets(packDir, manifest) {
  const skillSummaries = [];
  const promptSummaries = [];

  for (const skill of manifest.skills) {
    const absoluteSkillDir = path.join(packDir, skill.path);
    const skillEntryPath = path.join(absoluteSkillDir, "SKILL.md");

    if (!(await pathExists(absoluteSkillDir))) {
      throw new Error(`Missing skill directory for "${skill.id}": ${absoluteSkillDir}`);
    }

    if (!(await pathExists(skillEntryPath))) {
      throw new Error(`Skill "${skill.id}" must include SKILL.md: ${skillEntryPath}`);
    }

    const bytes = await directorySize(absoluteSkillDir);
    const fileCount = await countDirectoryFiles(absoluteSkillDir);
    const skillMarkdown = await readFile(skillEntryPath, "utf8");

    skillSummaries.push({
      id: skill.id,
      path: skill.path,
      bytes,
      fileCount,
      contextChars: skillMarkdown.length
    });
  }

  for (const prompt of manifest.prompts) {
    const absolutePromptPath = path.join(packDir, prompt.path);

    if (!(await pathExists(absolutePromptPath))) {
      throw new Error(`Missing prompt file for "${prompt.id}": ${absolutePromptPath}`);
    }

    const content = await readFile(absolutePromptPath, "utf8");

    promptSummaries.push({
      id: prompt.id,
      path: prompt.path,
      bytes: Buffer.byteLength(content, "utf8"),
      contextChars: content.length
    });
  }

  return { skillSummaries, promptSummaries };
}

function buildCatalog(manifest, skillSummaries, promptSummaries) {
  return {
    name: manifest.name,
    version: manifest.version,
    description: manifest.description,
    targets: manifest.targets,
    skills: skillSummaries,
    prompts: promptSummaries,
    estimatedContextChars:
      skillSummaries.reduce((sum, skill) => sum + skill.contextChars, 0) +
      promptSummaries.reduce((sum, prompt) => sum + prompt.contextChars, 0)
  };
}

function toPosixPath(value) {
  return value.split(path.sep).join("/");
}

function buildCodexAgentsFile(manifest) {
  const skillList = manifest.skills
    .map((skill) => `- \`${skill.id}\`: ${skill.description}`)
    .join("\n");

  return `# ${manifest.name} Codex Bundle

This bundle was generated by Packsmith.

Use these bundled skills when relevant:

${skillList}
`;
}

function buildTargetReadme(target, manifest) {
  const installHint =
    target === "claude-code"
      ? "Copy the bundled `skills/` directory into your Claude Code skills location, for example under `.claude/skills/<pack-name>/`."
      : "Keep the bundled `skills/` directory with your repo and use the generated `AGENTS.md` as the bridge document for Codex-oriented workflows.";

  return `# ${manifest.name} for ${target}

Generated by Packsmith.

## Included

- ${manifest.skills.length} skill(s)
- ${manifest.prompts.length} prompt(s)

## Install

${installHint}
`;
}

function buildPackManifest(packName) {
  return {
    name: packName,
    description: `Reusable skills for ${packName}.`,
    version: "0.1.0",
    targets: ["claude-code", "codex"],
    skills: [
      {
        id: "starter-skill",
        path: "skills/starter-skill",
        description: "Starter workflow for your first Packsmith skill."
      }
    ],
    prompts: [
      {
        id: "starter-prompt",
        path: "prompts/starter-prompt.md",
        description: "Starter prompt for launching a Packsmith pack."
      }
    ]
  };
}

async function emitTargetBundle(packDir, targetRoot, target, manifest) {
  await ensureDir(targetRoot);

  for (const skill of manifest.skills) {
    const source = path.join(packDir, skill.path);
    const targetDir = path.join(targetRoot, "skills", skill.id);
    await copyDirectory(source, targetDir);
  }

  for (const prompt of manifest.prompts) {
    const source = path.join(packDir, prompt.path);
    const targetFile = path.join(targetRoot, "prompts", path.basename(prompt.path));
    const promptContent = await readFile(source, "utf8");
    await writeText(targetFile, promptContent);
  }

  await writeText(path.join(targetRoot, "README.md"), buildTargetReadme(target, manifest));

  if (target === "codex") {
    await writeText(path.join(targetRoot, "AGENTS.md"), buildCodexAgentsFile(manifest));
  }

  await writeJson(path.join(targetRoot, "bundle.json"), {
    target,
    pack: manifest.name,
    version: manifest.version,
    generatedAt: new Date().toISOString(),
    skills: manifest.skills.map((skill) => ({
      id: skill.id,
      path: toPosixPath(path.join("skills", skill.id, "SKILL.md"))
    })),
    prompts: manifest.prompts.map((prompt) => ({
      id: prompt.id,
      path: toPosixPath(path.join("prompts", path.basename(prompt.path)))
    }))
  });
}

export async function validatePack(packDir) {
  const absolutePackDir = path.resolve(packDir);
  const { manifest } = await loadManifest(absolutePackDir);
  const { skillSummaries, promptSummaries } = await validateAssets(absolutePackDir, manifest);

  return {
    manifest,
    packDir: absolutePackDir,
    skillCount: skillSummaries.length,
    promptCount: promptSummaries.length
  };
}

export async function inspectPack(packDir) {
  const absolutePackDir = path.resolve(packDir);
  const { manifest } = await loadManifest(absolutePackDir);
  const { skillSummaries, promptSummaries } = await validateAssets(absolutePackDir, manifest);
  const catalog = buildCatalog(manifest, skillSummaries, promptSummaries);

  return {
    packDir: absolutePackDir,
    name: catalog.name,
    version: catalog.version,
    targets: catalog.targets,
    skillCount: catalog.skills.length,
    promptCount: catalog.prompts.length,
    estimatedContextChars: catalog.estimatedContextChars,
    skills: catalog.skills
  };
}

export async function buildPack(packDir, outDir = "dist") {
  const absolutePackDir = path.resolve(packDir);
  const { manifest } = await loadManifest(absolutePackDir);
  const { skillSummaries, promptSummaries } = await validateAssets(absolutePackDir, manifest);
  const outputRoot = path.join(absolutePackDir, outDir, manifest.name);
  const catalog = buildCatalog(manifest, skillSummaries, promptSummaries);

  await ensureDir(outputRoot);
  await writeJson(path.join(outputRoot, "manifest.json"), manifest);
  await writeJson(path.join(outputRoot, "catalog.json"), catalog);

  for (const target of manifest.targets) {
    const targetRoot = path.join(outputRoot, target);
    await emitTargetBundle(absolutePackDir, targetRoot, target, manifest);
  }

  return {
    manifest,
    outputRoot,
    targetsBuilt: manifest.targets
  };
}

export async function initPack(targetDir) {
  const absoluteTargetDir = path.resolve(targetDir);
  const packName = path.basename(absoluteTargetDir);
  const manifest = buildPackManifest(packName);
  const skillDir = path.join(absoluteTargetDir, "skills", "starter-skill");
  const promptPath = path.join(absoluteTargetDir, "prompts", "starter-prompt.md");

  await ensureDir(skillDir);
  await ensureDir(path.dirname(promptPath));
  await writeJson(path.join(absoluteTargetDir, "packsmith.json"), manifest);
  await writeText(
    path.join(skillDir, "SKILL.md"),
    `---
name: starter-skill
description: Starter Packsmith skill for ${packName}.
---

# Starter Skill

Use this skill as the first workflow in your new pack.

## Workflow

1. Define the user problem.
2. Collect the primary evidence.
3. End with one concrete recommendation.
`
  );
  await writeText(
    promptPath,
    `# Starter Prompt

You are shaping the first workflow for ${packName}.

Return:

- user
- problem
- evidence
- recommendation
`
  );

  return {
    packDir: absoluteTargetDir,
    manifest
  };
}

export async function installBundle(bundleDir, options = {}) {
  const absoluteBundleDir = path.resolve(bundleDir);
  const manifestPath = path.join(absoluteBundleDir, "manifest.json");

  if (!(await pathExists(manifestPath))) {
    throw new Error(`Missing built manifest: ${manifestPath}`);
  }

  const manifest = await readJson(manifestPath);
  const target = options.target ?? manifest.targets?.[0];

  if (!target || !SUPPORTED_TARGETS.has(target)) {
    throw new Error(`Install target must be one of: ${Array.from(SUPPORTED_TARGETS).join(", ")}.`);
  }

  const targetSourceDir = path.join(absoluteBundleDir, target);

  if (!(await pathExists(targetSourceDir))) {
    throw new Error(`Missing built target directory: ${targetSourceDir}`);
  }

  const destinationRoot = path.resolve(options.dest ?? path.join(absoluteBundleDir, "installed"));
  const installDir = path.join(destinationRoot, manifest.name);

  await copyDirectory(targetSourceDir, installDir);
  await copyFileOrDirectory(path.join(absoluteBundleDir, "manifest.json"), path.join(installDir, "manifest.json"));
  await copyFileOrDirectory(path.join(absoluteBundleDir, "catalog.json"), path.join(installDir, "catalog.json"));

  return {
    manifest,
    target,
    installDir
  };
}
